### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Gjum** [okx-code/civmodern#2]
Cloning and `./gradlew build` gives various errors when trying with various java versions.

Can you add detailed build instructions for fabric and forge to the Readme? Including build commands for each version, required java version, and other dependencies/requirements.

Thank you.

**Comment by okx-code** [comment]
Please post those errors? That is the command I am using

**Comment by Gjum** [comment]
```
$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9)
OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode)

$ ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Architect Plugin: 3.1.105
Architectury Loom: 0.6.111 Build(release #111)

> Configure project :common
:remapping 1 mods (TinyRemapper, intermediary -> named)
:remapping sources

FAILURE: Build failed with an exception.

* Where:
Build file '/.../civmodern/fabric/build.gradle'

* What went wrong:
Could not compile build file '/.../civmodern/fabric/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 60
  
  java.lang.IllegalArgumentException: Unsupported class file major version 60
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        (full stacktrace: https://gist.github.com/Gjum/eca1a3f80018a877567b49cf42912389)
  
  1 error


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 15s
```

**Comment by okx-code** [comment]
Downgrade your Java version. Unfortunately I am not able to update Gradle to a version supporting Java 16 because the plugins this mods depends on are not updated.

**Comment by Gjum** [comment]
For anyone running into this in the future: Java 11 (OpenJDK) worked, Java 8 and 16 didn't.
